### ISSUE TITLE
Error: The platform win32-x64 is not currently supported!

### ISSUE THREAD

**Issue by demskie** [google/node-gles#44]
>C:\Users\alexd\gpu-brick-sort>yarn add node-gles
>yarn add v1.16.0
>warning ..\..\..\package.json: No license field
>[1/4] Resolving packages...
>[2/4] Fetching packages...
>info fsevents@2.0.6: The platform "win32" is incompatible with this module.
>info "fsevents@2.0.6" is an optional dependency and failed compatibility check. Excluding it from installation.
>info fsevents@1.2.9: The platform "win32" is incompatible with this module.
>info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
>[3/4] Linking dependencies...
>warning " > raw-loader@3.1.0" has unmet peer dependency "webpack@^4.3.0".
>[4/4] Building fresh packages...
>error C:\Users\alexd\gpu-brick-sort\node_modules\node-gles: Command failed.
>Exit code: 1
>Command: node scripts/install.js
>Arguments:
>Directory: C:\Users\alexd\gpu-brick-sort\node_modules\node-gles
>Output:
>C:\Users\alexd\gpu-brick-sort\node_modules\node-gles\scripts\install.js:44
>  throw new Error(`The platform ${platformArch} is not currently supported!`);
>  ^
>
>Error: The platform win32-x64 is not currently supported!
>    at Object.<anonymous> (C:\Users\alexd\gpu-brick-sort\node_modules\node-gles\scripts\install.js:44:9)
>    at Module._compile (internal/modules/cjs/loader.js:805:30)
>    at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
>    at Module.load (internal/modules/cjs/loader.js:672:32)
>    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
>    at Function.Module._load (internal/modules/cjs/loader.js:604:3)
>    at Function.Module.runMain (internal/modules/cjs/loader.js:868:12)
>    at internal/main/run_main_module.js:21:11
>info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

The README says windows support is planned

**Comment by molst** [comment]
I can confirm this is still the case:
`Error: The platform win32-x64 is not currently supported!`

It seems [quick search in google/angle](https://github.com/google/angle/search?q=win64&unscoped_q=win64) should support it so I suppose it should be an easy fix.
