### ISSUE TITLE
Add Windows support

### ISSUE THREAD

**Issue by nkreeger** [google/node-gles#61]
1.) Provide a pre-built version of ANGLE for Windows (chromium/3729).
2.) Update scripts/install.js to handle Windows download
3.) Update binding.gyp (see tfjs-node for reference code).

**Comment by broerse** [comment]
If I run `npm install `

```

> node-gles@0.0.16 install C:\dev\node-gles\node_modules\node-gles
> node scripts/install.js

C:\dev\node-gles\node_modules\node-gles\scripts\install.js:44
  throw new Error(`The platform ${platformArch} is not currently supported!`);
  ^

Error: The platform win32-x64 is not currently supported!
    at Object.<anonymous> (C:\dev\node-gles\node_modules\node-gles\scripts\install.js:44:9)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-gles@0.0.16 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-gles@0.0.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Martin\AppData\Roaming\npm-cache\_logs\2019-09-26T18_45_27_433Z-debug.log

C:\dev\node-gles>
```
and if I run `npm install` with the current github master it install fine but `const nodeGles = require('node-gles');` is in the readme cant find the `node-gles` module. It seems there is something wrong with the bindings.

**Comment by molst** [comment]
Please see my comment on this duplicate issue https://github.com/google/node-gles/issues/44
