### ISSUE TITLE
Specified module not found (windows 10)

### ISSUE THREAD

**Issue by nipmarsh** [google/node-gles#70]
Error: Le module spécifié est introuvable.
\\?\F:\Lapin\api\node_modules\node-gles\build\Release\nodejs_gl_binding.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:730:18)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at bindings (F:\Lapin\api\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (F:\Lapin\api\node_modules\node-gles\dist\index.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)

**Comment by Prior99** [comment]
I have the same issue.

**Comment by felicemarra** [comment]
Same also for me. Any solution?

**Comment by felicemarra** [comment]
I got the same error also in Ubuntu 18
